"""
blockchain.py
--------------
Python-side blockchain access, using web3.py to talk to Ganache.
Used by admin/backend scripts (device registration, revocation) and by
zero_trust.py (permission checks + audit log writes). The React
frontend ALSO talks to the same contracts directly via ethers.js/
MetaMask for user-triggered actions - both paths hit the same Ganache
node, so state always stays consistent no matter which side wrote it.

Reads contract addresses from .env and ABIs from contracts_abi/*.json
(these JSON files are generated by blockchain/scripts/deploy.js - see
that file's comments for exactly what it writes and where).
"""

import json
import os

from dotenv import load_dotenv
from web3 import Web3

load_dotenv()

RPC_URL = os.getenv("GANACHE_RPC_URL", "http://127.0.0.1:7545")
ADMIN_PRIVATE_KEY = os.getenv("ADMIN_PRIVATE_KEY")

DEVICE_IDENTITY_ADDRESS = os.getenv("DEVICE_IDENTITY_CONTRACT_ADDRESS")
ACCESS_CONTROL_ADDRESS = os.getenv("ACCESS_CONTROL_CONTRACT_ADDRESS")
AUDIT_LOG_ADDRESS = os.getenv("AUDIT_LOG_CONTRACT_ADDRESS")

ABI_DIR = os.path.join(os.path.dirname(__file__), "contracts_abi")

w3 = Web3(Web3.HTTPProvider(RPC_URL))


def _load_abi(contract_name: str):
    path = os.path.join(ABI_DIR, f"{contract_name}.json")
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)["abi"]


def _contract(name: str, address: str):
    abi = _load_abi(name)
    if abi is None or not address:
        return None
    return w3.eth.contract(address=Web3.to_checksum_address(address), abi=abi)


def get_admin_account():
    if not ADMIN_PRIVATE_KEY:
        raise RuntimeError("ADMIN_PRIVATE_KEY not set in .env")
    return w3.eth.account.from_key(ADMIN_PRIVATE_KEY)


def _send(contract_fn):
    """Signs and sends a state-changing transaction using unlocked accounts
    or admin private key, ensuring funds exist, and returns tx receipt info."""
    try:
        if not w3.is_connected():
            return {"status": "SKIPPED", "reason": "Ethereum RPC node not reachable"}

        # If local dev node has unlocked accounts and accounts[0] is available, use it directly
        if len(w3.eth.accounts) > 0:
            admin_addr = w3.eth.accounts[0]
            tx_hash = contract_fn.transact({"from": admin_addr})
            receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
            return {
                "tx_hash": tx_hash.hex(),
                "block_number": receipt.blockNumber,
                "status": "SUCCESS" if receipt.status == 1 else "FAILED",
            }

        # Otherwise sign with ADMIN_PRIVATE_KEY
        account = get_admin_account()
        tx = contract_fn.build_transaction({
            "from": account.address,
            "nonce": w3.eth.get_transaction_count(account.address),
            "gas": 3_000_000,
            "gasPrice": w3.eth.gas_price,
        })
        signed = account.sign_transaction(tx)
        raw_tx = getattr(signed, "raw_transaction", getattr(signed, "rawTransaction", None))
        tx_hash = w3.eth.send_raw_transaction(raw_tx)
        receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
        return {
            "tx_hash": tx_hash.hex(),
            "block_number": receipt.blockNumber,
            "status": "SUCCESS" if receipt.status == 1 else "FAILED",
        }
    except Exception as e:
        return {"status": "ERROR", "reason": str(e)}


# ---------------- DeviceIdentity.sol ----------------

def register_device_onchain(device_id, device_type, did, device_address, role):
    contract = _contract("DeviceIdentity", DEVICE_IDENTITY_ADDRESS)
    if contract is None:
        return {"status": "SKIPPED", "reason": "DeviceIdentity contract not configured yet"}
    return _send(contract.functions.registerDevice(
        device_id, device_type, did, device_address, role
    ))


def revoke_device_onchain(device_id):
    contract = _contract("DeviceIdentity", DEVICE_IDENTITY_ADDRESS)
    if contract is None:
        return {"status": "SKIPPED", "reason": "DeviceIdentity contract not configured yet"}
    return _send(contract.functions.revokeDevice(device_id))


def activate_device_onchain(device_id):
    contract = _contract("DeviceIdentity", DEVICE_IDENTITY_ADDRESS)
    if contract is None:
        return {"status": "SKIPPED", "reason": "DeviceIdentity contract not configured yet"}
    return _send(contract.functions.activateDevice(device_id))


def is_device_active_onchain(device_id) -> bool:
    try:
        contract = _contract("DeviceIdentity", DEVICE_IDENTITY_ADDRESS)
        if contract is None:
            return True  # fail-open to PostgreSQL status only if contract isn't deployed yet
        return contract.functions.isDeviceActive(device_id).call()
    except Exception:
        return True


# ---------------- AccessControl.sol ----------------

def grant_permission_onchain(role, resource, action):
    contract = _contract("AccessControl", ACCESS_CONTROL_ADDRESS)
    if contract is None:
        return {"status": "SKIPPED", "reason": "AccessControl contract not configured yet"}
    return _send(contract.functions.grantPermission(role, resource, action))


def revoke_permission_onchain(role, resource, action):
    contract = _contract("AccessControl", ACCESS_CONTROL_ADDRESS)
    if contract is None:
        return {"status": "SKIPPED", "reason": "AccessControl contract not configured yet"}
    return _send(contract.functions.revokePermission(role, resource, action))


DEFAULT_ROLE_PERMISSIONS = {
    ("SENSOR", "Temperature", "READ"): True,
    ("SENSOR", "Humidity", "READ"): True,
    ("SENSOR", "Motion", "READ"): True,
    ("SENSOR", "DoorStatus", "READ"): True,
    ("CAMERA", "CameraFeed", "READ"): True,
    ("ACTUATOR", "GarageDoor", "WRITE"): True,
    ("ACTUATOR", "MotorControl", "WRITE"): True,
}


def check_permission_onchain(role, resource, action) -> bool:
    try:
        contract = _contract("AccessControl", ACCESS_CONTROL_ADDRESS)
        if contract is None:
            return DEFAULT_ROLE_PERMISSIONS.get((role, resource, action), False)
        return contract.functions.hasPermission(role, resource, action).call()
    except Exception:
        return DEFAULT_ROLE_PERMISSIONS.get((role, resource, action), False)


# ---------------- AuditLog.sol ----------------

def record_audit_log(device_id, resource, action, decision):
    contract = _contract("AuditLog", AUDIT_LOG_ADDRESS)
    if contract is None:
        return {"status": "SKIPPED", "reason": "AuditLog contract not configured yet"}
    return _send(contract.functions.logEvent(device_id, resource, action, decision))


def get_audit_trail(limit=50):
    try:
        contract = _contract("AuditLog", AUDIT_LOG_ADDRESS)
        if contract is None:
            return []
        total = contract.functions.getEventCount().call()
        start = max(0, total - limit)
        events = []
        for i in range(start, total):
            events.append(contract.functions.getEvent(i).call())
        return events
    except Exception:
        return []


if __name__ == "__main__":
    print("Connected to Ganache:", w3.is_connected())
    if w3.is_connected():
        print("Chain ID:", w3.eth.chain_id)
        print("Latest block:", w3.eth.block_number)

